server:
  port: 80

spring:
  application:
    name: log

logging:
  level:
    root: WARN
    com.cooperzhu: INFO
  file:
    path: /opt

userconfig:
  aliyun:
    cdn:
       end-point: "cdn.aliyuncs.com" # aliyun cdn end-point
       access-key-id: xxx   # aliyun accessKeyId
       access-key-secret: xxx  # aliyun accessKeySecret
  task:
    period: 30  # unit: min
